### ISSUE TITLE
fie start的时候自动安装 fie-toolkit-qnui 报错

### ISSUE THREAD

**Issue by effert** [fieteam/fie-toolkit-qnui#11]
以下是错误信息：
Error: connect ETIMEDOUT 100.67.95.39:80
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)

[fie-error] 安装 @ali/fie-toolkit-qnui@latest 出错,请确认网络是否正常及包名是否输入正确。
我ping了一下也确实ping不通100.67.95.39:80。

**Comment by effert** [comment]
要用fie switch 切换成外网，在安装就可以了
